### ISSUE TITLE
Improve organization of script for updating Artsy repos

### ISSUE THREAD

**Issue by jonallured** [jonallured/dotfiles#55]
While working on #54 I got this:

```
jon@magneto:~/code/allocation(artsy-repos)% ruby artsy_repos.rb > ~/code/team-artsy-workflow-data/data/repos.yml
Traceback (most recent call last):
	34: from artsy_repos.rb:8:in `<main>'
	33: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/octokit-4.13.0/lib/octokit/client/organizations.rb:126:in `organization_repositories'
	32: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/octokit-4.13.0/lib/octokit/connection.rb:88:in `paginate'
	31: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/sawyer-0.8.1/lib/sawyer/relation.rb:163:in `get'
	30: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/sawyer-0.8.1/lib/sawyer/relation.rb:264:in `call'
	29: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	28: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.3/lib/faraday/connection.rb:138:in `get'
	27: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.3/lib/faraday/connection.rb:387:in `run_request'
	26: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.3/lib/faraday/rack_builder.rb:143:in `build_response'
	25: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.3/lib/faraday/request/retry.rb:128:in `call'
	24: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/octokit-4.13.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	23: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/octokit-4.13.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	22: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.3/lib/faraday/response.rb:8:in `call'
	21: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.3/lib/faraday/response.rb:8:in `call'
	20: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:38:in `call'
	19: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
	18: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:43:in `block in call'
	17: from /Users/jon/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:85:in `perform_request'
	16: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1213:in `get'
	15: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1455:in `request'
	14: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:910:in `start'
	13: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1457:in `block in request'
	12: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1464:in `request'
	11: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1502:in `transport_request'
	10: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:165:in `reading_body'
	 9: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1503:in `block in transport_request'
	 8: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1214:in `block in get'
	 7: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:204:in `read_body'
	 6: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:283:in `read_body_0'
	 5: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:264:in `inflater'
	 4: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:285:in `block in read_body_0'
	 3: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:324:in `read_chunked'
	 2: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:324:in `ensure in read_chunked'
	 1: from /Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:125:in `read'
/Users/jon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:189:in `rbuf_fill': end of file reached (Faraday::ConnectionFailed)
```

But it worked on Colossus, so I'm not sure what's going on there.

Also: the way I have this setup is stupid - I should consider another way of organizing this type of script.

**Comment by jonallured** [comment]
☝️ this hasn't happened in a few weeks, so I'm not sure what was up with that error however, I still want to have another think about how I organize these types of scripts. I've updated the title of this one to reflect this.

**Comment by jonallured** [comment]
I ended up renaming the allocations repo to github_scripts so I'm going to close this sucker.
